#!/usr/bin/python

import os, sys

"""
173-128-235-175:~ paul$ sudo port deps gperf
gperf has no dependencies
173-128-235-175:~ paul$ sudo port deps glib2
glib2 has build dependencies on:
	pkgconfig
glib2 has library dependencies on:
	gettext
	libiconv
	perl5
	python_select
"""

indent = 0
deps = set()

def get_deps(package):
	global indent
	indent += 1
	for dep in os.popen('port deps %s' % package):
		if not dep.startswith('\t'): # dependencies are indented
			continue
		dep = dep.strip()
		if dep not in deps:
			print '  '*indent + dep
			get_deps(dep)
		else:
			print '  '*indent + '*' + dep
		deps.add(dep)
	indent -= 1

if __name__ == '__main__':
	if len(sys.argv) < 2:
		print "usage: %s package" % sys.argv[0]
		sys.exit(0)
	dep = sys.argv[1]
	print dep
	get_deps(dep)

